### ISSUE TITLE
Android X migration is not complete

### ISSUE THREAD

**Issue by Elizabeth-Mezias-Bose** [googlesamples/android-JumpingJack#2]
The MainActivity class import is using Android Jetpack.
import androidx.wear.ambient.AmbientModeSupport;

However, the build.gradle does not declare AndroidX. Instead of:
androidx.wear:wear:1.0.0

you find the following dependencies:
implementation 'com.google.android.gms:play-services-wearable:16.0.1'
    implementation 'com.android.support:support-v13:28.0.0'
    compileOnly 'com.google.android.wearable:wearable:2.4.0'
    implementation 'com.google.android.support:wearable:2.4.0'

That means the project won't build if you import this sample.

**Comment by codingjeremy** [comment]
This issue has been migrated to the new wear-os repo [here](https://github.com/android/wear-os/issues/11).

Updates will followup there. Thank you!
